# Site settings
title: Steve Do
email: steve.do@hotmail.com
url: https://github.com/SteveDo1
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Cybersecurity & GRC Analyst - Passionate about Cybersecurity"
meta_author: Do Steve

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5fa8d3
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 1b4965
  secondary-dark: 233140 #A2122F
  about: bee9e8

# Footer settings
footer:
  copyright: Steve Do
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stevedo1/
  - title: github
    url: https://github.com/SteveDo1

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
